config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  	registrations: "users/registrations"
  }

  get "users/logout"

	# root "appointments#index"

  root "appointments#home"

	post "appointments/:id/signup" => 'appointments#signup'

  get 'appointments/index' => 'appointments#index'

	get 'users/show', to: 'users#show'

	delete '/appointments/:id' => 'appointments#destroy' 

  get '/reviews/:id/new' => 'reviews#new'

  post '/reviews/:id' => 'reviews#create'

  get '/reviews/:id/show' => 'reviews#show'

  resources :appointments

end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :mentor, class_name: "User"
	belongs_to :student, class_name: "User", optional: true
	validate :scheduled_in_the_future
	validates :start_time, presence: true
	validates :topic, presence: true
	validates :interval, presence: true
	has_many :reviews

	def scheduled_in_the_future
		if start_time.past?
			errors.add(:start_time, "Scheduled start time can not be in the past.")
		end
	end

	def verify_datetime(params)
		if ( /\d{2}.\d{2}.\d{4}/.match(params[:date]) ) == nil
			return false
		elsif params[:date].count('/') != 2
			return false
		elsif params[:start_time].count(":") != 1
			return false
		elsif params[:start_time].split(":").length != 2
			return false
		elsif params[:start_time][-2..-1].downcase != "pm" && "am"
			return false
		else
			return true
		end	
	end

	def generate_start_time(params)
		date = params[:date].split('/')
		year = date[2].to_i
		month = date[0].to_i
		day = date[1].to_i
		time = params[:start_time].split(':')
		if time[1][-2..-1].downcase == 'pm'
			hour = time[0].to_i + 12
		elsif time[1][-2..-1].downcase == 'am'
			hour = time[0].to_i
		end
		time[1].slice!(-2..-1)
		minute = time[1].to_i
		d = DateTime.new(year, month, day, hour, minute)
		(d.to_time + 6.hours).to_datetime

	end

	def generate_end_time(params)
		start_time = self.generate_start_time(params)
		start_time + params[:appointment][:interval].to_i.minutes
	end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  include AppointmentsHelper
  # GET /appointments
  # GET /appointments.json

  def home
  end 

  def signup
    redirect_to(new_user_session_path) and return if !current_user
    appt = Appointment.find(params[:id])
    if appt.mentor != current_user
      appt.available = false
      appt.student = current_user
      appt.save
    end
    redirect_to("/appointments/index")
  end 

  def index
    redirect_to(new_user_session_path) and return if !current_user
    filter_past_appointments(Appointment.all)
    @appointments = Appointment.where(available: true)
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    redirect_to(new_user_session_path) and return if !current_user
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new
    if @appointment.verify_datetime(params) == false
      @error = "Please enter a valid date and time."
      render('new') and return
    else
      @appointment.topic = params[:appointment][:topic]
      @appointment.start_time = @appointment.generate_start_time(params)
      @appointment.end_time = @appointment.generate_end_time(params)
      @appointment.interval = params[:appointment][:interval].to_i
      @appointment.available = true
      @appointment.mentor = current_user
      if @appointment.save
        redirect_to "/appointments/index"
      else
        render "new"
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])
    @appointment.available = true
    @appointment.student_id = nil
    @appointment.save
    if @appointment.save
      redirect_to :back and return
    else
      flash[:notice] = "Post successfully created"
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    Appointment.find(params[:id]).destroy
    redirect_to :back
  end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
	def display_datetime(appt)
		local_time( (appt.start_time.to_time - 6.hours).to_datetime )
	end

	def filter_past_appointments(appointments)
		appointments.each do |appt|
			if appt.start_time < DateTime.now && appt.available
				appt.available = false
				appt.save
			end
		end
	end

	def past_appointment?(appt)

	end
end

app/views/appointments/_form.html.erb
<%= form_for @appointment, html: {class: "form-register"} do |f| %>
  <div class="form-register-with-email">
    <div class="form-white-background">
      <div class="form-title-row">
        <!-- optional -->
        <h1> New Appointment </h1>
      </div>
      <div class="field">
        <%= f.label :topic %><br>
        <%= f.text_field :topic, placeholder: 'Biology' %>
      </div>
      <div class="field">
        <%= f.label :date %><br>
        <input type="text" name="date" placeholder="01/16/1998">
      </div> <br>
      <div class="field">
        <%= f.label :start_time %><br>
        <input type="text" name="start_time" placeholder="5:30pm">
      </div>
      <div class="field">
        <%= f.label :interval %><br>
        <%= f.select :interval, ['30', '60']%> <span class="form-min"> minutes </span>
      </div>
      <div class="form-row">
        <input type="submit" value="Post Opening" class="btn auth-btn" id="appt-new">
      </div>
    </div>
  </div>
<% end %>

<% if @error %>
  <%= @error %>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>
<%= link_to 'Back', appointments_path %>

app/views/appointments/home.html.erb
    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>Appointment Scheduler</h1>
            <h2>Click below to sign up for a lesson or mentor another student</h2>
            <br>
            <a href="/appointments/new" class="btn btn-dark btn-lg index-btn">Mentor</a>
            <a href="/appointments" class="btn btn-dark btn-lg index-btn">Student</a>
        </div>
    </header>

    <!-- About -->
    <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Connect with other students in your community</h2>
                    <p class="lead">Schedule a session to mentor a student, or sign up to be tutored as a student</p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

app/views/appointments/index.html.erb
<div class="appointments-index">
<% if @appointments.length > 0 %>
	<h1>Appointments</h1>
	<ul>
		<% @appointments.each do |appt| %>
			<li>
				<h2> <%= appt.topic %> | <%= appt.mentor.first_name %> <%= appt.mentor.last_name[0].upcase %>. </h2>
				<h3>
				<%= display_datetime(appt) %>
				(<%= appt.interval %> mins)
				</h3>
				<form action="/appointments/<%= appt.id %>/signup" method="post">
					<input type="submit" value="Sign Up" class="btn appt-index-btn" style="margin-top: 10px;">
				</form>
			</li>
		<% end %>
	</ul>
<% else %>
	<h1> There are currently no openings </h1>
<% end %>
</div>

app/views/appointments/new.html.erb
<div class="appointment-div">
	<%= render 'form', appointment: @appointment %>
</div>